// <auto-generated />
using System;
using AP.MyGameStore.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AP.MyGameStore.Infrastructure.Migrations
{
    [DbContext(typeof(MyGameStoreContext))]
    [Migration("20240912170554_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AP.MyGameStore.Domain.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EmailAddress");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblPeople", "Person");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bert@bibber.com",
                            EmployerId = 1,
                            FirstName = "Bert",
                            Gender = 1,
                            LastName = "Bibber"
                        });
                });

            modelBuilder.Entity("AP.MyGameStore.Domain.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Addition")
                        .IsRequired()
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Place");

                    b.Property<bool>("IsFranchiseStore")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Zipcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblStores", "Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Addition = "",
                            City = "Kortrijk",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Kortrijk",
                            Number = "260",
                            Street = "Korte Steenstraat",
                            Zipcode = "8500"
                        },
                        new
                        {
                            Id = 2,
                            Addition = "",
                            City = "Ninove",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Ninove",
                            Number = "95",
                            Street = "Centrumlaan",
                            Zipcode = "9400"
                        },
                        new
                        {
                            Id = 3,
                            Addition = "",
                            City = "Roeselare",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Roeselare",
                            Number = "97",
                            Street = "Ooststraat",
                            Zipcode = "8800"
                        },
                        new
                        {
                            Id = 4,
                            Addition = "",
                            City = "Zaventem",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Zaventem",
                            Number = "173",
                            Street = "Weiveldlaan",
                            Zipcode = "1930"
                        },
                        new
                        {
                            Id = 5,
                            Addition = "",
                            City = "Hasselt",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Hasselt",
                            Number = "254",
                            Street = "Demerstraat",
                            Zipcode = "3500"
                        },
                        new
                        {
                            Id = 6,
                            Addition = "",
                            City = "Gent",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Gent",
                            Number = "128",
                            Street = "Veldstraat",
                            Zipcode = "9000"
                        },
                        new
                        {
                            Id = 7,
                            Addition = "",
                            City = "Knokke-Heist",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Knokke-Heist",
                            Number = "215",
                            Street = "Lippenslaan",
                            Zipcode = "8300"
                        },
                        new
                        {
                            Id = 8,
                            Addition = "",
                            City = "Maaseik",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Maaseik",
                            Number = "239",
                            Street = "Bosstraat",
                            Zipcode = "3680"
                        },
                        new
                        {
                            Id = 9,
                            Addition = "",
                            City = "Beringen",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Beringen",
                            Number = "85",
                            Street = "Koolmijnlaan",
                            Zipcode = "3580"
                        },
                        new
                        {
                            Id = 10,
                            Addition = "",
                            City = "Geraardsbergen",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Geraardsbergen",
                            Number = "149",
                            Street = "Winkelstraat",
                            Zipcode = "9500"
                        },
                        new
                        {
                            Id = 11,
                            Addition = "",
                            City = "Asse",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Asse",
                            Number = "260",
                            Street = "Stationsstraat",
                            Zipcode = "1730"
                        },
                        new
                        {
                            Id = 12,
                            Addition = "",
                            City = "Geel",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Geel",
                            Number = "59",
                            Street = "Nieuwstraat",
                            Zipcode = "2440"
                        },
                        new
                        {
                            Id = 13,
                            Addition = "",
                            City = "Antwerpen",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Antwerpen",
                            Number = "76",
                            Street = "Meir",
                            Zipcode = "2000"
                        },
                        new
                        {
                            Id = 14,
                            Addition = "",
                            City = "Mol",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Mol",
                            Number = "179",
                            Street = "Statiestraat",
                            Zipcode = "2400"
                        },
                        new
                        {
                            Id = 15,
                            Addition = "",
                            City = "Sint-Gillis",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Sint-Gillis",
                            Number = "286",
                            Street = "Fonsnylaan",
                            Zipcode = "1060"
                        },
                        new
                        {
                            Id = 16,
                            Addition = "4",
                            City = "Ieper",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Ieper",
                            Number = "189",
                            Street = "Boterstraat",
                            Zipcode = "8900"
                        },
                        new
                        {
                            Id = 17,
                            Addition = "",
                            City = "Aalst",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Aalst",
                            Number = "64",
                            Street = "Nieuwstraat",
                            Zipcode = "3800"
                        },
                        new
                        {
                            Id = 18,
                            Addition = "B",
                            City = "Mechelen",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Mechelen",
                            Number = "106",
                            Street = "Bruul",
                            Zipcode = "2800"
                        },
                        new
                        {
                            Id = 19,
                            Addition = "",
                            City = "Jette",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Jette",
                            Number = "78",
                            Street = "Léon Theodorstraat",
                            Zipcode = "1090"
                        },
                        new
                        {
                            Id = 20,
                            Addition = "",
                            City = "Schaarbeek",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Schaarbeek",
                            Number = "18",
                            Street = "Helmetsesteenweg",
                            Zipcode = "1030"
                        },
                        new
                        {
                            Id = 21,
                            Addition = "",
                            City = "Dendermonde",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Dendermonde",
                            Number = "206",
                            Street = "Oude Vest",
                            Zipcode = "9200"
                        },
                        new
                        {
                            Id = 22,
                            Addition = "",
                            City = "Sint-Niklaas",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Sint-Niklaas",
                            Number = "299",
                            Street = "Stationsstraat",
                            Zipcode = "9100"
                        },
                        new
                        {
                            Id = 23,
                            Addition = "A",
                            City = "Turnhout",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Turnhout",
                            Number = "40",
                            Street = "Gasthuisstraat",
                            Zipcode = "2300"
                        },
                        new
                        {
                            Id = 24,
                            Addition = "",
                            City = "Brecht",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Brecht",
                            Number = "18",
                            Street = "Heiken",
                            Zipcode = "2960"
                        },
                        new
                        {
                            Id = 25,
                            Addition = "",
                            City = "Sint-Jans-Molenbeek",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Sint-Jans-Molenbeek",
                            Number = "191",
                            Street = "Schoolstraat",
                            Zipcode = "1080"
                        },
                        new
                        {
                            Id = 26,
                            Addition = "",
                            City = "Brasschaat",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Brasschaat",
                            Number = "26",
                            Street = "Bredabaan",
                            Zipcode = "2930"
                        },
                        new
                        {
                            Id = 27,
                            Addition = "2",
                            City = "Halle",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Halle",
                            Number = "187",
                            Street = "Basiliekstraat",
                            Zipcode = "1500"
                        },
                        new
                        {
                            Id = 28,
                            Addition = "",
                            City = "Stokkem",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Dilsen-Stokkem",
                            Number = "236",
                            Street = "Rijksweg",
                            Zipcode = "3650"
                        },
                        new
                        {
                            Id = 29,
                            Addition = "",
                            City = "Schoten",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Schoten",
                            Number = "77",
                            Street = "Paalstraat",
                            Zipcode = "2900"
                        },
                        new
                        {
                            Id = 30,
                            Addition = "H",
                            City = "Genk",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Genk",
                            Number = "141",
                            Street = "Molenstraat",
                            Zipcode = "3600"
                        },
                        new
                        {
                            Id = 31,
                            Addition = "",
                            City = "Harelbeke",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Harelbeke",
                            Number = "184",
                            Street = "Tramstraat",
                            Zipcode = "8530"
                        },
                        new
                        {
                            Id = 32,
                            Addition = "",
                            City = "Wevelgem",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Wevelgem",
                            Number = "192",
                            Street = "Menenstraat",
                            Zipcode = "8560"
                        },
                        new
                        {
                            Id = 33,
                            Addition = "",
                            City = "Elsene",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Elsene",
                            Number = "135",
                            Street = "Elsensesteenweg",
                            Zipcode = "1050"
                        },
                        new
                        {
                            Id = 34,
                            Addition = "",
                            City = "Vilvoorde",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Vilvoorde",
                            Number = "68",
                            Street = "Leuvensestraat",
                            Zipcode = "1800"
                        },
                        new
                        {
                            Id = 35,
                            Addition = "",
                            City = "Leuven",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Leuven",
                            Number = "83",
                            Street = "Diestsestraat",
                            Zipcode = "3000"
                        },
                        new
                        {
                            Id = 36,
                            Addition = "",
                            City = "Anderlecht",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Anderlecht",
                            Number = "29",
                            Street = "Olympische Dreef",
                            Zipcode = "1070"
                        },
                        new
                        {
                            Id = 37,
                            Addition = "",
                            City = "Grimbergen",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Grimbergen",
                            Number = "264",
                            Street = "Hogesteenweg",
                            Zipcode = "1850"
                        },
                        new
                        {
                            Id = 38,
                            Addition = "5",
                            City = "Ukkel",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Ukkel",
                            Number = "170",
                            Street = "Verrewinkelstraat",
                            Zipcode = "1180"
                        },
                        new
                        {
                            Id = 39,
                            Addition = "A",
                            City = "Deinze",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Deinze",
                            Number = "180",
                            Street = "Winkelstraat",
                            Zipcode = "9800"
                        },
                        new
                        {
                            Id = 40,
                            Addition = "",
                            City = "Brussel",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Brussel",
                            Number = "104",
                            Street = "Louizalaan",
                            Zipcode = "1000"
                        },
                        new
                        {
                            Id = 41,
                            Addition = "",
                            City = "Waregem",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Waregem",
                            Number = "172",
                            Street = "Stationsstraat",
                            Zipcode = "8790"
                        },
                        new
                        {
                            Id = 42,
                            Addition = "",
                            City = "Brugge",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Brugge",
                            Number = "176",
                            Street = "Steenstraat",
                            Zipcode = "8000"
                        },
                        new
                        {
                            Id = 43,
                            Addition = "",
                            City = "Sint-Lambrechts-Woluwe",
                            IsFranchiseStore = true,
                            Name = "MyGameStore Sint-Lambrechts-Woluwe",
                            Number = "35",
                            Street = "Konkelstraat",
                            Zipcode = "1200"
                        },
                        new
                        {
                            Id = 44,
                            Addition = "",
                            City = "Lommel",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Lommel",
                            Number = "157",
                            Street = "Kerkstraat",
                            Zipcode = "3920"
                        },
                        new
                        {
                            Id = 45,
                            Addition = "",
                            City = "Evergem",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Evergem",
                            Number = "41",
                            Street = "Noorwegenstraat",
                            Zipcode = "9940"
                        },
                        new
                        {
                            Id = 46,
                            Addition = "",
                            City = "Lier",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Lier",
                            Number = "169",
                            Street = "Antwerpsestraat",
                            Zipcode = "2500"
                        },
                        new
                        {
                            Id = 47,
                            Addition = "",
                            City = "Sint-Truiden",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Sint-Truiden",
                            Number = "76",
                            Street = "Luikerstraat",
                            Zipcode = "3800"
                        },
                        new
                        {
                            Id = 48,
                            Addition = "C",
                            City = "Aarschot",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Aarschot",
                            Number = "16",
                            Street = "Martelarenstraat",
                            Zipcode = "3200"
                        },
                        new
                        {
                            Id = 49,
                            Addition = "",
                            City = "Oostende",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Oostende",
                            Number = "149",
                            Street = "Kapellestraat",
                            Zipcode = "8400"
                        },
                        new
                        {
                            Id = 50,
                            Addition = "",
                            City = "Lokeren",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Lokeren",
                            Number = "2",
                            Street = "Kerkstraat",
                            Zipcode = "9160"
                        },
                        new
                        {
                            Id = 51,
                            Addition = "",
                            City = "Tienen",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Tienen",
                            Number = "183",
                            Street = "Leuvensestraat",
                            Zipcode = "3300"
                        },
                        new
                        {
                            Id = 52,
                            Addition = "",
                            City = "Vorst",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Vorst",
                            Number = "132",
                            Street = "Neerstalse Steenweg",
                            Zipcode = "1190"
                        },
                        new
                        {
                            Id = 53,
                            Addition = "",
                            City = "Dilbeek",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Dilbeek",
                            Number = "39",
                            Street = "Verheydenstraat",
                            Zipcode = "1700"
                        },
                        new
                        {
                            Id = 54,
                            Addition = "E",
                            City = "Bilzen",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Bilzen",
                            Number = "97",
                            Street = "Hees",
                            Zipcode = "3740"
                        },
                        new
                        {
                            Id = 55,
                            Addition = "",
                            City = "Tongeren",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Tongeren",
                            Number = "44",
                            Street = "Maastrichterstraat",
                            Zipcode = "3700"
                        },
                        new
                        {
                            Id = 56,
                            Addition = "",
                            City = "Sint-Pieters-Leeuw",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Sint-Pieters-Leeuw",
                            Number = "97",
                            Street = "Rink",
                            Zipcode = "1600"
                        },
                        new
                        {
                            Id = 57,
                            Addition = "",
                            City = "Beveren",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Beveren",
                            Number = "62",
                            Street = "Vrasenestraat",
                            Zipcode = "8791"
                        },
                        new
                        {
                            Id = 58,
                            Addition = "1",
                            City = "Bree",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Bree",
                            Number = "68",
                            Street = "Gerdingerstraat",
                            Zipcode = "3960"
                        },
                        new
                        {
                            Id = 59,
                            Addition = "",
                            City = "Menen",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Menen",
                            Number = "142",
                            Street = "Rijselstraat",
                            Zipcode = "8930"
                        },
                        new
                        {
                            Id = 60,
                            Addition = "",
                            City = "Berg",
                            IsFranchiseStore = false,
                            Name = "MyGameStore Heist-op-den-Berg",
                            Number = "39",
                            Street = "Bergstraat",
                            Zipcode = "1910"
                        });
                });

            modelBuilder.Entity("AP.MyGameStore.Domain.Person", b =>
                {
                    b.HasOne("AP.MyGameStore.Domain.Store", "Employer")
                        .WithMany("Employees")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("AP.MyGameStore.Domain.Store", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
